version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - scripts
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - scripts
      - third_party$
      - builtin$
      - examples$
