name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      # - name: Install package
      #   run: |
      #     sudo apt install -y libpcap-dev
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.3.0
      - name: Run GoReleaser
        timeout-minutes: 60
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
